# Generated by Django 2.2.1 on 2019-05-31 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='章节名称')),
                ('synopsis', models.CharField(max_length=300, null=True, verbose_name='章节简介')),
                ('num', models.CharField(default='第一章', max_length=30)),
                ('create_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('up_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '章节表',
                'verbose_name_plural': '章节表',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='视频名称')),
                ('synopsis', models.CharField(max_length=300, null=True, verbose_name='视频简介')),
                ('cover', models.ImageField(null=True, upload_to='course/video/img/', verbose_name='视频封面')),
                ('need_time', models.IntegerField(verbose_name='视频时长')),
                ('video_type', models.IntegerField(blank=True, default=2, verbose_name=((1, '项目视频'), (2, '课程视频')))),
                ('url', models.FileField(max_length=200, upload_to='course/video/video/', verbose_name='视频地址')),
                ('create_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('chapter_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Chapter', verbose_name='所属章节id')),
            ],
            options={
                'verbose_name': '视频表',
                'verbose_name_plural': '视频表',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('inner', models.CharField(blank=True, max_length=300, verbose_name='笔记内容')),
                ('status', models.IntegerField(choices=[(0, '屏蔽'), (1, '展示')], default=1, verbose_name='当前状态')),
                ('create_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('chapter_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Chapter', verbose_name='所属章节id')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '笔记表',
                'verbose_name_plural': '笔记表',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='课程名称')),
                ('need_time', models.IntegerField(default=0, verbose_name='需要时长')),
                ('synopsis', models.CharField(max_length=50, verbose_name='课程简介')),
                ('study_len', models.IntegerField(default=0, verbose_name='学习人数')),
                ('career_direction', models.CharField(default='全部', max_length=50, verbose_name='职业方向标签')),
                ('classification', models.CharField(default='全部', max_length=50, verbose_name='分类标签')),
                ('cover', models.ImageField(null=True, upload_to='course/', verbose_name='课程封面')),
                ('leave', models.IntegerField(choices=[(1, '入门'), (2, '初级'), (3, '中级'), (4, '高级')], default=1, null=True, verbose_name='难易程度')),
                ('status', models.IntegerField(choices=[(0, '下架'), (1, '上架')], default=1, null=True, verbose_name='课程当前状态')),
                ('buy', models.IntegerField(choices=[(0, '未购买'), (1, '已购买')], default=0, verbose_name='是否购买课程')),
                ('buy_channel', models.IntegerField(choices=[(1, '支付宝'), (2, '微信'), (3, '信用卡'), (4, '储蓄卡'), (5, '积分兑换')], default=1, verbose_name='购买渠道')),
                ('create_times', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('score', models.IntegerField(default=5, verbose_name='评分')),
                ('project_id', models.ManyToManyField(to='subject.ProjectDetail', verbose_name='相关项目')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course', verbose_name='所属的课程id'),
        ),
    ]
