# Generated by Django 2.1.7 on 2019-05-24 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='章节名称')),
                ('synopsis', models.CharField(max_length=300, null=True, verbose_name='章节简介')),
                ('cover', models.ImageField(null=True, upload_to='course/chapter/', verbose_name='章节封面')),
                ('create_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('up_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('course_id', models.IntegerField(verbose_name='所属的课程id')),
            ],
            options={
                'verbose_name': '章节表',
                'verbose_name_plural': '章节表',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='课程名称')),
                ('need_time', models.IntegerField(default=0, verbose_name='需要时长')),
                ('synopsis', models.CharField(max_length=50, verbose_name='课程简介')),
                ('study_len', models.IntegerField(default=0, verbose_name='学习人数')),
                ('career_direction', models.CharField(default='全部', max_length=50, verbose_name='职业方向标签')),
                ('classification', models.CharField(default='全部', max_length=50, verbose_name='分类标签')),
                ('cover', models.ImageField(null=True, upload_to='course/', verbose_name='课程封面')),
                ('leave', models.IntegerField(choices=[(1, '入门'), (2, '初级'), (3, '中级'), (4, '高级')], default=1, null=True, verbose_name='难易程度')),
                ('yin', models.IntegerField(choices=[(0, '隐'), (1, '不隐')], default=0, null=True)),
                ('create_times', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='视频名称')),
                ('synopsis', models.CharField(max_length=300, null=True, verbose_name='视频简介')),
                ('cover', models.ImageField(null=True, upload_to='course/video/img/', verbose_name='视频封面')),
                ('need_time', models.IntegerField(verbose_name='视频时长')),
                ('url', models.FileField(max_length=200, upload_to='course/video/video/', verbose_name='视频地址')),
                ('create_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('chapter_id', models.IntegerField(verbose_name='所属章节id')),
            ],
            options={
                'verbose_name': '视频表',
                'verbose_name_plural': '视频表',
            },
        ),
    ]
