# Generated by Django 2.2.1 on 2019-05-28 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('chapter_id', models.IntegerField(verbose_name='所属章节id')),
                ('inner', models.CharField(blank=True, max_length=300, verbose_name='笔记内容')),
                ('status', models.IntegerField(choices=[(0, '屏蔽'), (1, '展示')], default=1, verbose_name='当前状态')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('create_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '笔记表',
                'verbose_name_plural': '笔记表',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='yin',
        ),
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.IntegerField(choices=[(0, '未学习'), (1, '学习中'), (2, '已学习')], default=0, verbose_name='是否学习'),
        ),
        migrations.AddField(
            model_name='course',
            name='buy',
            field=models.IntegerField(choices=[(0, '未购买'), (1, '已购买')], default=0, verbose_name='是否购买课程'),
        ),
        migrations.AddField(
            model_name='course',
            name='buy_channel',
            field=models.IntegerField(choices=[(1, '支付宝'), (2, '微信'), (3, '信用卡'), (4, '储蓄卡'), (5, '积分兑换')], default=1, verbose_name='购买渠道'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, '下架'), (1, '上架')], default=1, null=True, verbose_name='课程当前状态'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.IntegerField(blank=True, default=2, verbose_name=((1, '项目视频'), (2, '课程视频'))),
        ),
    ]
