# Generated by Django 2.2.1 on 2019-05-29 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190529_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='章节名称')),
                ('synopsis', models.CharField(max_length=300, null=True, verbose_name='章节简介')),
                ('cover', models.ImageField(null=True, upload_to='course/chapter/', verbose_name='章节封面')),
                ('status', models.IntegerField(choices=[(0, '未学习'), (1, '学习中'), (2, '已学习')], default=0, verbose_name='是否学习')),
                ('create_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('up_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '章节详细表',
                'verbose_name_plural': '章节详细表',
            },
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='score',
            field=models.IntegerField(default=5, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='note',
            name='chapter_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.ChapterData', verbose_name='所属章节id'),
        ),
        migrations.AddField(
            model_name='chapterdata',
            name='course_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Chapter', verbose_name='所属的章节id'),
        ),
    ]
