# Generated by Django 2.2.1 on 2019-06-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190601_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.IntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0, verbose_name='章节完成度'),
        ),
    ]
