# Generated by Django 2.2.1 on 2019-05-31 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190529_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='chapter_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Chapter', verbose_name='所属章节id'),
        ),
        migrations.DeleteModel(
            name='ChapterData',
        ),
    ]
