# Generated by Django 2.2.1 on 2019-06-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190601_1647'),
        ('course', '0003_chapter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='knowledge',
            field=models.ImageField(blank='', default='', null='', upload_to='', verbose_name='思维导图(知识点)'),
        ),
        migrations.AddField(
            model_name='video',
            name='blog',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Blog', verbose_name='相关博客'),
        ),
    ]
