# Generated by Django 2.2.1 on 2019-06-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190601_1647'),
        ('course', '0004_auto_20190604_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='blog',
        ),
        migrations.AddField(
            model_name='chapter',
            name='blog',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Blog', verbose_name='相关博客'),
        ),
    ]
