# Generated by Django 2.2.1 on 2019-06-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20190604_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='blog',
            field=models.ManyToManyField(blank=True, to='blog.Blog', verbose_name='相关博客'),
        ),
    ]
