# Generated by Django 2.2.1 on 2019-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='num',
            field=models.CharField(default='第一章', max_length=30),
        ),
    ]
