# Generated by Django 2.2.1 on 2019-05-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_last_login',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='慧码用户1559183054985', max_length=30, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_joined',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='注册IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_last_login',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='uuid'),
        ),
    ]
