# Generated by Django 2.2.1 on 2019-05-29 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_last_login',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_joined',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='注册IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_last_login',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='最后登录IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.IntegerField(blank=True, null=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.IntegerField(blank=True, null=True, verbose_name='uuid'),
        ),
    ]
