# Generated by Django 2.2.1 on 2019-06-01 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        ('course', '0002_auto_20190601_1647'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='favoritecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='favoritecourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户'),
        ),
    ]
