# Generated by Django 2.2.1 on 2019-06-01 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190601_1647'),
        ('subject', '0001_initial'),
        ('user', '0002_auto_20190601_2025'),
        ('task', '0001_initial'),
        ('operation', '0002_auto_20190601_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='回复时间')),
                ('like_num', models.IntegerField(default=0, verbose_name='被点赞数')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='回复博客')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '博客回复表',
                'verbose_name_plural': '博客回复表',
                'ordering': ['add_time'],
            },
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='评论')),
                ('like_num', models.IntegerField(default=0, verbose_name='被点赞数')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.Questions', verbose_name='试题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户试题',
                'verbose_name_plural': '用户试题',
            },
        ),
        migrations.CreateModel(
            name='UserBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='初始浏览时间')),
                ('last_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后浏览时间')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='收藏')),
                ('favorite_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间')),
                ('is_like', models.BooleanField(default=False, verbose_name='点赞')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Blog', verbose_name='博客')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户博客',
                'verbose_name_plural': '用户博客',
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='初始点击时间')),
                ('last_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后点击时间')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='收藏')),
                ('favorite_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间')),
                ('is_like', models.BooleanField(default=False, verbose_name='点赞')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subject.ProjectDetail', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户项目',
                'verbose_name_plural': '用户项目',
            },
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='初始点击时间')),
                ('last_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后点击时间')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='收藏')),
                ('favorite_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间')),
                ('is_like', models.BooleanField(default=False, verbose_name='点赞')),
                ('is_correct', models.BooleanField(default=False, verbose_name='回答正确')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.Questions', verbose_name='试题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户试题',
                'verbose_name_plural': '用户试题',
            },
        ),
        migrations.AlterModelOptions(
            name='coursecomment',
            options={'verbose_name': '课程评论', 'verbose_name_plural': '课程评论'},
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='like_num',
            field=models.BooleanField(default=False, verbose_name='被点赞数'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='favorite_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='收藏'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='is_like',
            field=models.BooleanField(default=False, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='comment',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course', verbose_name='评论课程'),
        ),
        migrations.DeleteModel(
            name='FavoriteCourse',
        ),
    ]
