# Generated by Django 2.2.1 on 2019-06-04 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_chapter_status'),
        ('user', '0003_auto_20190604_1011'),
        ('operation', '0003_auto_20190601_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment2',
            options={'ordering': ['add_time'], 'verbose_name': '博客回复', 'verbose_name_plural': '博客回复'},
        ),
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'verbose_name': '试题评论', 'verbose_name_plural': '试题评论'},
        ),
        migrations.AlterModelOptions(
            name='userblog',
            options={'verbose_name': '博客用户', 'verbose_name_plural': '博客用户'},
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '课程用户', 'verbose_name_plural': '课程用户'},
        ),
        migrations.AlterModelOptions(
            name='userproject',
            options={'verbose_name': '项目用户', 'verbose_name_plural': '项目用户'},
        ),
        migrations.AlterModelOptions(
            name='userquestion',
            options={'verbose_name': '试题用户', 'verbose_name_plural': '试题用户'},
        ),
        migrations.AlterField(
            model_name='blogcomment2',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='回复博客名'),
        ),
        migrations.AlterField(
            model_name='blogcomment2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course', verbose_name='评论课程名'),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.Questions', verbose_name='试题名'),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Blog', verbose_name='博客名'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course', verbose_name='课程名'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='favorite_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='是否收藏'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='is_like',
            field=models.BooleanField(default=False, verbose_name='是否点赞'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subject.ProjectDetail', verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.Questions', verbose_name='试题名'),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='VideoQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2048, verbose_name='内容')),
                ('is_reply_user', models.BooleanField(default=False, verbose_name='是否是回复别人')),
                ('reply_user', models.IntegerField(default=0, verbose_name='被回复人ID')),
                ('status', models.BooleanField(default=False, verbose_name='激活状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户名')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Video', verbose_name='视频名')),
            ],
            options={
                'verbose_name': '视频问答',
                'verbose_name_plural': '视频问答',
            },
        ),
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='初始点击时间')),
                ('is_like', models.BooleanField(default=False, verbose_name='点赞')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户名')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Video', verbose_name='视频名')),
            ],
            options={
                'verbose_name': '用户视频',
                'verbose_name_plural': '用户视频',
            },
        ),
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='初始点击时间')),
                ('last_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后点击时间')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='收藏')),
                ('favorite_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间')),
                ('is_like', models.BooleanField(default=False, verbose_name='点赞')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Chapter', verbose_name='章节名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户章节',
                'verbose_name_plural': '用户章节',
            },
        ),
        migrations.CreateModel(
            name='ChapterQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Q')),
                ('answer', models.CharField(max_length=255, verbose_name='A')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Chapter', verbose_name='章节名')),
            ],
            options={
                'verbose_name': '章节QA',
                'verbose_name_plural': '章节QA',
            },
        ),
    ]
