# Generated by Django 2.2.1 on 2019-05-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('proj_desc', models.CharField(max_length=1024, verbose_name='项目简介')),
                ('proj_start', models.CharField(blank=True, max_length=1024, null=True, verbose_name='项目开始')),
                ('proj_start_dt', models.DateTimeField(blank=True, max_length=1024, null=True, verbose_name='项目开始完成时间')),
                ('proj_start_status', models.IntegerField(choices=[(0, '未完成'), (1, '完成')], default=0, verbose_name='项目开始状态')),
                ('proj_introduce', models.CharField(max_length=1024, verbose_name='功能介绍')),
                ('proj_introduce_dt', models.DateTimeField(blank=True, max_length=1024, null=True, verbose_name='功能介绍完成时间')),
                ('proj_introduce_status', models.IntegerField(choices=[(0, '未完成'), (1, '完成')], default=0, verbose_name='功能介绍状态')),
                ('proj_baseskill', models.CharField(blank=True, max_length=1024, null=True, verbose_name='基础技能')),
                ('proj_baseskill_dt', models.DateTimeField(blank=True, max_length=1024, null=True, verbose_name='基础技能完成时间')),
                ('proj_baseskill_status', models.IntegerField(choices=[(0, '未完成'), (1, '完成')], default=0, verbose_name='基础技能状态')),
                ('proj_display', models.CharField(blank=True, max_length=1024, null=True, verbose_name='项目展示')),
                ('proj_display_dt', models.DateTimeField(blank=True, max_length=1024, null=True, verbose_name='项目展示完成时间')),
                ('proj_display_status', models.IntegerField(choices=[(0, '未完成'), (1, '完成')], default=0, verbose_name='项目展示状态')),
                ('proj_aboutread', models.CharField(blank=True, max_length=1024, null=True, verbose_name='相关阅读')),
                ('proj_aboutread_dt', models.DateTimeField(blank=True, max_length=1024, null=True, verbose_name='相关阅读完成时间')),
                ('proj_aboutread_status', models.IntegerField(choices=[(0, '未完成'), (1, '完成')], default=0, verbose_name='相关阅读状态')),
                ('proj_download', models.CharField(blank=True, max_length=1024, null=True, verbose_name='资料下载')),
                ('proj_download_dt', models.DateTimeField(blank=True, max_length=1024, null=True, verbose_name='资料下载完成时间')),
                ('proj_download_status', models.IntegerField(choices=[(0, '未完成'), (1, '完成')], default=0, verbose_name='资料下载状态')),
                ('proj_video', models.URLField(blank=True, max_length=1024, null=True, verbose_name='相关视频')),
                ('proj_video_dt', models.DateTimeField(blank=True, max_length=1024, null=True, verbose_name='相关视频完成时间')),
                ('proj_video_status', models.IntegerField(choices=[(0, '未完成'), (1, '完成')], default=0, verbose_name='相关视频状态')),
                ('proj_upload', models.CharField(blank=True, max_length=1024, null=True, verbose_name='上传项目')),
                ('proj_upload_dt', models.DateTimeField(blank=True, max_length=1024, null=True, verbose_name='上传项目完成时间')),
                ('proj_upload_status', models.IntegerField(choices=[(0, '未完成'), (1, '完成')], default=0, verbose_name='上传项目状态')),
                ('proj_senior', models.CharField(blank=True, max_length=1024, null=True, verbose_name='进阶教程')),
                ('proj_senior_dt', models.DateTimeField(blank=True, max_length=1024, null=True, verbose_name='进阶教程完成时间')),
                ('proj_senior_status', models.IntegerField(choices=[(0, '未完成'), (1, '完成')], default=0, verbose_name='进阶教程状态')),
                ('proj_finish', models.CharField(blank=True, max_length=1024, null=True, verbose_name='项目终点')),
                ('proj_finish_status', models.IntegerField(choices=[(0, '未完成'), (1, '完成')], default=0, verbose_name='进阶教程状态')),
                ('proj_arrowleft', models.ImageField(blank=True, null=True, upload_to='', verbose_name='左箭头')),
                ('proj_arrowright', models.ImageField(blank=True, null=True, upload_to='', verbose_name='右箭头')),
                ('proj_arrowdown', models.ImageField(blank=True, null=True, upload_to='', verbose_name='下箭头')),
                ('proj_arrowup', models.ImageField(blank=True, null=True, upload_to='', verbose_name='上箭头')),
                ('proj_date', models.DateTimeField(blank=True, null=True, verbose_name='项目完成日期')),
                ('proj_statu', models.IntegerField(choices=[(0, '未完成'), (1, '完成')], default=0, verbose_name='项目状态')),
                ('proj_text', models.TextField(blank=True, null=True, verbose_name='留言板')),
                ('proj_bg_img', models.ImageField(blank=True, default='media/1.jpg', null=True, upload_to='', verbose_name='项目背景图')),
                ('proj_progress', models.IntegerField(default=0, verbose_name='项目进度')),
                ('proj_level', models.IntegerField(choices=[(0, '初级'), (1, '中级'), (2, '高级')], default=0, verbose_name='项目难度')),
                ('proj_student', models.IntegerField(default=0, verbose_name='学习人数')),
                ('proj_teacher', models.CharField(blank=True, max_length=1024, null=True, verbose_name='指导老师')),
                ('proj_tag', models.CharField(blank=True, max_length=1024, null=True, verbose_name='项目标签')),
                ('proj_howlong', models.SmallIntegerField(default=1, verbose_name='项目时长')),
            ],
            options={
                'verbose_name': '项目详细表1',
                'verbose_name_plural': '项目详细表1222',
                'db_table': '项目详细表',
                'get_latest_by': 'proj_date',
                'db_tablespace': 'proj_date',
                'managed': True,
                'order_with_respect_to': 'proj_name',
            },
        ),
    ]
