# Generated by Django 2.2.1 on 2019-05-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdetail',
            options={'verbose_name': '项目详细表', 'verbose_name_plural': '项目详细表'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='projectdetail',
            order_with_respect_to=None,
        ),
    ]
