# Generated by Django 2.2.1 on 2019-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='proj_cover',
            field=models.ImageField(default='media/a.jpg', upload_to='media/project/', verbose_name='项目背景'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='proj_arrowdown',
            field=models.ImageField(blank=True, null=True, upload_to='media/project', verbose_name='下箭头'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='proj_arrowleft',
            field=models.ImageField(blank=True, null=True, upload_to='media/project', verbose_name='左箭头'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='proj_arrowright',
            field=models.ImageField(blank=True, null=True, upload_to='media/project', verbose_name='右箭头'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='proj_arrowup',
            field=models.ImageField(blank=True, null=True, upload_to='media/project', verbose_name='上箭头'),
        ),
    ]
