# Generated by Django 2.2.1 on 2019-05-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectdetail',
            table=None,
        ),
    ]
