# Generated by Django 2.2.1 on 2019-06-01 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionsBank_name', models.CharField(max_length=500, verbose_name='题库名称')),
                ('QuestionsBank_describe', models.CharField(blank=True, max_length=700, null=True, verbose_name='题库简介')),
                ('create_time', models.DateField(blank=True, null=True, verbose_name='创建时间')),
                ('schedule', models.IntegerField(blank=True, null=True, verbose_name='进度时间')),
                ('its_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', '基础任务'), ('2', '进阶任务')], default='基础任务', max_length=20, verbose_name='任务类别')),
                ('title', models.CharField(max_length=500, verbose_name='任务题目')),
                ('questions_img', models.ImageField(blank=True, null=True, upload_to='questions_img/%Y/%m/%d')),
                ('select_answer_A', models.CharField(default='', max_length=200, verbose_name='选项A')),
                ('select_answer_B', models.CharField(default='', max_length=200, verbose_name='选项B')),
                ('select_answer_C', models.CharField(blank=True, max_length=200, null=True, verbose_name='选项C')),
                ('select_answer_D', models.CharField(blank=True, max_length=200, null=True, verbose_name='选项D')),
                ('select_answer_E', models.CharField(blank=True, max_length=200, null=True, verbose_name='选项E')),
                ('select_answer_F', models.CharField(blank=True, max_length=200, null=True, verbose_name='选项F')),
                ('select_answer_G', models.CharField(blank=True, max_length=200, null=True, verbose_name='选项G')),
                ('answer', models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C'), ('3', 'D'), ('4', 'E'), ('5', 'F'), ('6', 'G')], max_length=20, verbose_name='正确答案')),
                ('create_time', models.DateField(blank=True, null=True, verbose_name='创建时间')),
                ('schedule', models.IntegerField(blank=True, null=True, verbose_name='进度时间')),
                ('its_QuestionsBank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.QuestionsBank', verbose_name='所属题库')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
    ]
