# Generated by Django 2.2.1 on 2019-05-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsbank',
            options={'verbose_name': '题库', 'verbose_name_plural': '题库'},
        ),
    ]
