# Generated by Django 2.2.1 on 2019-06-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='慧码用户1559391923123', max_length=30, verbose_name='昵称'),
        ),
    ]
