# Generated by Django 2.2.1 on 2019-06-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190601_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='慧码用户1559614289999', max_length=30, verbose_name='昵称'),
        ),
    ]
