# Generated by Django 2.2.1 on 2019-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0002_auto_20190530_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='慧码用户1559183976335', max_length=30, verbose_name='昵称'),
        ),
    ]
