# Generated by Django 2.2.1 on 2019-05-31 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('front_image', models.ImageField(default='', upload_to='blog/%Y/%m', verbose_name='博客封面图')),
                ('content', models.TextField(verbose_name='正文')),
                ('publish', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('com_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('tag_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Category', verbose_name='语言id')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Level', verbose_name='分类id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='博主id')),
            ],
            options={
                'verbose_name': '博客表',
                'verbose_name_plural': '博客表',
                'ordering': ['publish'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('publish', models.DateTimeField(auto_now=True, verbose_name='回复时间')),
                ('tag_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='回复博客')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '博客回复表',
                'verbose_name_plural': '博客回复表',
                'ordering': ['publish'],
            },
        ),
    ]
