# Generated by Django 2.2.1 on 2019-05-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0003_category_level'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='blog_id',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usercenter.Category', verbose_name='语言id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usercenter.Level', verbose_name='分类id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usercenter.User', verbose_name='博主id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='回复博客'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usercenter.User', verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='com_num',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='tag_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
