# Generated by Django 2.2.1 on 2019-05-31 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(upload_to='banner/%Y/%m')),
                ('banner_img_title', models.CharField(max_length=500, verbose_name='轮播图片名称')),
                ('banner_img_nub', models.IntegerField(verbose_name='轮播图片序号')),
                ('banner_img_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='轮播图片链接')),
                ('banner_img_introduce', models.CharField(blank=True, max_length=500, null=True, verbose_name='轮播图片内容')),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_email', '修改邮箱')], max_length=30, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
    ]
